name: MoMentum
channels:
- !!python/unicode
  'glemaitre'
- !!python/unicode
  'sloria'
- !!python/unicode
  'asmeurer'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'beautiful-soup=4.3.2=py27_0'
- !!python/unicode
  'click=6.7=py27_0'
- !!python/unicode
  'cycler=0.10.0=py27_0'
- !!python/unicode
  'flask=0.12=py27_0'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'functools32=3.2.3.2=py27_0'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'itsdangerous=0.24=py27_0'
- !!python/unicode
  'jinja2=2.9.5=py27_0'
- !!python/unicode
  'libiconv=1.14=0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'libxml2=2.9.4=0'
- !!python/unicode
  'libxslt=1.1.29=0'
- !!python/unicode
  'lxml=3.7.3=py27_0'
- !!python/unicode
  'markupsafe=0.23=py27_2'
- !!python/unicode
  'matplotlib=2.0.0=np112py27_0'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'nltk=3.2.2=py27_0'
- !!python/unicode
  'numpy=1.12.0=py27_0'
- !!python/unicode
  'openssl=1.0.2k=0'
- !!python/unicode
  'pandas=0.19.2=np112py27_1'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'pyparsing=2.1.4=py27_0'
- !!python/unicode
  'pyqt=5.6.0=py27_2'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'python-dateutil=2.6.0=py27_0'
- !!python/unicode
  'pytz=2016.10=py27_0'
- !!python/unicode
  'qt=5.6.2=0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'requests=2.13.0=py27_0'
- !!python/unicode
  'scikit-learn=0.18.1=np112py27_1'
- !!python/unicode
  'scipy=0.18.1=np112py27_1'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'sip=4.18=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'sqlalchemy=1.1.5=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'subprocess32=3.2.7=py27_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'werkzeug=0.11.15=py27_0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
- !!python/unicode
  'imbalanced-learn=0.2.1=py27_0'
- !!python/unicode
  'textblob=0.9.1=py27_0'
- pip:
  - beautifulsoup4==4.3.2
  - xmltodict==0.10.2
